# The URL the site will be built for
base_url = "https://stephanmeesters.nl"
default_language = "en"
theme = "amemone"
compile_sass = false
build_search_index = true
minify_html = false
lazy_async_image = false

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
favicon = "favicon.ico"
image = ""

default_theme = "dark"
list_pages = false
twitter_card = true

header_nav = [
  { url = "/", name_en = "/home/", name_fr = "/accueil/" },
  { url = "/software-development", name_en = "/software/" },
  { url = "/games", name_en = "/games/" },
]
