# The URL the site will be built for
base_url = "https://stephanmeesters.nl"
default_language = "en"
theme = "amemone"
compile_sass = false
build_search_index = true
default_theme = "dark"

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
